import type { Metadata } from "next";
import "./styles.css"
// import { Providers } from "./provider";
import Header from "@/components/Header";
import Footer from "@/components/Footer";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body

            >
                {/* <Providers> */}
                <Header />
                {children}
                <Footer/>
                {/* </Providers> */}
            </body>
        </html>
    );
}
